export const POST_COMMENTS = 'POST_COMMENTS';
export const SET_COMMENT = 'SET_COMMENT';
export const COMMENTS_REQUEST = 'COMMENTS_REQUEST';
export const COMMENTS_FAILURE = 'COMMENTS_FAILURE';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';