export const HOME_POSTS_REQUEST = 'HOME_POSTS_REQUEST';
export const HOME_POSTS_SUCCESS = 'HOME_POSTS_SUCCESS';
export const HOME_POSTS_FAILURE = 'HOME_POSTS_FAILURE';
export const GET_HOME_POSTS = 'HOME_POSTS_MORE';
export const EMPTY_HOME_POSTS = 'EMPTY_HOME_POSTS';
export const USER_POSTS_REQUEST = 'USER_POSTS_REQUEST';
export const USER_POSTS_SUCCESS = 'USER_POSTS_SUCCESS';
export const USER_POSTS_FAILURE = 'USER_POSTS_FAILURE';
export const LIKE_POST_REQUEST = 'LIKE_POST_REQUEST';
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS';
export const LIKE_POST_FAILURE = 'LIKE_POST_FAILURE';

