export const HOME_POSTS_REQUEST = 'HOME_POSTS_REQUEST';
export const HOME_POSTS_SUCCESS = 'HOME_POSTS_SUCCESS';
export const HOME_POSTS_FAILURE = 'HOME_POSTS_FAILURE';
export const GET_HOME_POSTS = 'HOME_POSTS_MORE';
export const EMPTY_HOME_POSTS = 'EMPTY_HOME_POSTS';