export const HOME_POSTS_REQUEST = 'HOME_POSTS_REQUEST';
export const HOME_POSTS_SUCCESS = 'HOME_POSTS_SUCCESS';
export const HOME_POSTS_FAILURE = 'HOME_POSTS_FAILURE';
export const SEARCH_POSTS_REQUEST = 'SEARCH_POSTS_REQUEST';
export const SEARCH_POSTS_SUCCESS = 'SEARCH_POSTS_SUCCESS';
export const SEARCH_POSTS_FAILURE = 'SEARCH_POSTS_FAILURE';