export const POST_REQUEST = 'POST_REQUEST';
export const POST_FAILURE = 'POST_FAILURE';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS'
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';