export const POST_REQUEST = 'POST_REQUEST';
export const POST_FAILURE = 'POST_FAILURE';
export const CLEAN_POSTS = 'CLEAN_POSTS';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS'
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

// NEW HANDLERS
export const USER_LIKE_REQUEST = 'USER_LIKE_REQUEST';
export const USER_LIKE_SUCCESS = 'USER_LIKE_SUCCESS';
export const USER_LIKE_FAILURE = 'USER_LIKE_FAILURE';